//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("github.trondr LogViewer description")]
[assembly: AssemblyCompany("github.trondr")]
[assembly: AssemblyProduct("LogViewer.Library")]
[assembly: AssemblyCopyright("Copyright © github.trondr 2017")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.17063.4.b47c439")]
[assembly: AssemblyVersion("1.0.17063.4")]
[assembly: AssemblyFileVersion("1.0.17063.4")]


