//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogViewer.Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF20B2AA")]
        public global::System.Windows.Media.Color DebugColor {
            get {
                return ((global::System.Windows.Media.Color)(this["DebugColor"]));
            }
            set {
                this["DebugColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA9A9A9")]
        public global::System.Windows.Media.Color TraceColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TraceColor"]));
            }
            set {
                this["TraceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000FF")]
        public global::System.Windows.Media.Color InfoColor {
            get {
                return ((global::System.Windows.Media.Color)(this["InfoColor"]));
            }
            set {
                this["InfoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA07A")]
        public global::System.Windows.Media.Color WarnColor {
            get {
                return ((global::System.Windows.Media.Color)(this["WarnColor"]));
            }
            set {
                this["WarnColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDB7093")]
        public global::System.Windows.Media.Color ErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ErrorColor"]));
            }
            set {
                this["ErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color FatalColor {
            get {
                return ((global::System.Windows.Media.Color)(this["FatalColor"]));
            }
            set {
                this["FatalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchFilter {
            get {
                return ((string)(this["SearchFilter"]));
            }
            set {
                this["SearchFilter"] = value;
            }
        }
    }
}
