//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("LogViewerogViewer is a log4j log viewer")]
[assembly: AssemblyCompany("github.trondr")]
[assembly: AssemblyProduct("github.trondr.LogViewer.Library")]
[assembly: AssemblyCopyright("Copyright © github.trondr 2016")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.16094.2.4fc277a")]
[assembly: AssemblyVersion("1.0.16094.2")]
[assembly: AssemblyFileVersion("1.0.16094.2")]


